* [32mmain[m
  rytvinski-hw2[m
  rytvinski-hw3[m
  [31mremotes/origin/3[m
  [31mremotes/origin/Baravik-hw2[m
  [31mremotes/origin/Baravik-hw3[m
  [31mremotes/origin/Bondarenko[m
  [31mremotes/origin/Bortsov[m
  [31mremotes/origin/Bykau[m
  [31mremotes/origin/Bykau-hw3[m
  [31mremotes/origin/Chukava-hw2[m
  [31mremotes/origin/Gerashchenko-HW-2[m
  [31mremotes/origin/HEAD[m -> origin/main
  [31mremotes/origin/Homework-3-Seliavko[m
  [31mremotes/origin/Katin[m
  [31mremotes/origin/KirylovichVadzim[m
  [31mremotes/origin/Komar-HW-3[m
  [31mremotes/origin/Koptev-Egor[m
  [31mremotes/origin/Koptev-Egor-HW2[m
  [31mremotes/origin/Koptev-Egor-HW3[m
  [31mremotes/origin/Krasnapiorau_Natan_HW[m
  [31mremotes/origin/Krasouski-Daniil-Seviaryn[m
  [31mremotes/origin/Kudriavceva-HW-2[m
  [31mremotes/origin/Lemesh_Homeworks[m
  [31mremotes/origin/Lyskov_hw2[m
  [31mremotes/origin/Melehov-hm2[m
  [31mremotes/origin/Melehov-hm3[m
  [31mremotes/origin/Melehov-hm4[m
  [31mremotes/origin/MikitaTsiarentsyeu-patch-1[m
  [31mremotes/origin/Nazaruk_Yurii[m
  [31mremotes/origin/NikitaStepanenko[m
  [31mremotes/origin/Paskovskij[m
  [31mremotes/origin/Seliavko-homework-3[m
  [31mremotes/origin/ShchurkoAndrei--HW[m
  [31mremotes/origin/Siamionava-hw2[m
  [31mremotes/origin/Siamionava-hw3[m
  [31mremotes/origin/Siamionava-hw4[m
  [31mremotes/origin/Timofey-Tsvetkov[m
  [31mremotes/origin/Tsikhanovich[m
  [31mremotes/origin/Viartsinskaya_hometasks[m
  [31mremotes/origin/bahachova-hw2[m
  [31mremotes/origin/bahachova-hw3[m
  [31mremotes/origin/belovAlexanderHW2[m
  [31mremotes/origin/belovHomework3[m
  [31mremotes/origin/eldar-hw2[m
  [31mremotes/origin/homework-02-verkhovodko[m
  [31mremotes/origin/homework-03-verkhovodko[m
  [31mremotes/origin/homeworks-kyrylin[m
  [31mremotes/origin/ioda-homework[m
  [31mremotes/origin/isaevi-homework[m
  [31mremotes/origin/ishchuk-hw2[m
  [31mremotes/origin/kazdym[m
  [31mremotes/origin/liauchuk_hw2[m
  [31mremotes/origin/liauchuk_hw3[m
  [31mremotes/origin/main[m
  [31mremotes/origin/murashka[m
  [31mremotes/origin/murashka_hw_3[m
  [31mremotes/origin/rytvinski-hw2[m
  [31mremotes/origin/seliavko[m
  [31mremotes/origin/seliavko-homework[m
  [31mremotes/origin/simanchuk-hw2[m
  [31mremotes/origin/simanchuk-hw3[m
  [31mremotes/origin/simanchuk-hw4[m
  [31mremotes/origin/tsiarentsyeu-homework-02[m
  [31mremotes/origin/tsiarentsyeu-hw[m
  [31mremotes/origin/tsiarentsyeu-hw-2[m
  [31mremotes/origin/tsiarentsyeu-hw2[m
